POST http://localhost:3001/api/allergy
content-type:application/json

{
 "Nombre": "Alergia a metales"
}

###
//ruta errorea hay que arreglar la att:lucho
GET http://localhost:3001/api/user/62c0be59b15d799447907381